Feature/tci 1220 1218 location page deployments
JudicialCouncilOfCalifornia/trialcourt pull request #4835
Opened 2024-12-10 21:43 UTC by adityajoshi94

2024-12-10 21:45 UTC, adityajoshi94 commented
@ivanbueno-jcc  For your code review

2024-12-12 23:54 UTC, ivanbueno-jcc requested changes
Merge the latest master into your branch.

2024-12-12 23:54 UTC, ivanbueno-jcc commented on web/modules/custom/jcc_custom/jcc_custom.install
> +      $vocabulary = Vocabulary::create([
Is this still needed?  Verify vocabularies are created by configs in immutable; not dbup.

2024-12-12 23:54 UTC, ivanbueno-jcc commented on config/config-alameda/.gitignore
>  core.entity_form_display.node.remote_hearings.default.yml
Run lando config-ignore.  I don't see your immutable fields here.

2025-06-12 19:17 UTC, closed without merging